### ISSUE TITLE
Tests fail (with Data::Object 0.41?)

### ISSUE THREAD

**Issue by eserte** [alnewkirk/Data-Seek#2]
The t/data/seek/exception.t test fails, possibly only if a rather new Data::Object (0.41) is installed:
```
#   Failed test at t/data/seek/exception.t line 24.
#          got: 'Data::Object::Exception::throw'
#     expected: '(eval)'
# Looks like you failed 1 test of 13.
t/data/seek/exception.t ...... 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/13 subtests 
```

**Comment by eserte** [comment]
Test suite fails also with Data::Object 0.35 and 0.40.

**Comment by alnewkirk** [comment]
Hey Slaven,

Thanks for pointing this out. I'm going to take care of it this week. I'll
update you once this has been resolved.

Thanks again,

Al

**Comment by alnewkirk** [comment]
Thanks again for pointing this out. This issue has been resolved in the latest release.
